import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const interDisplay = localFont({
  src: [
    {
      path: "../public/fonts/inter-display/InterVariable.ttf",
      style: "normal",
    },
    {
      path: "../public/fonts/inter-display/InterVariable-Italic.ttf",
      style: "italic",
    },
  ],
  variable: "--font-inter-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${interDisplay.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
